server:
  port: 8080

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          # Auth Service address to get Public Key to check signature
          issuer-uri: ${OAuth2_BASE_URL}
  application:
    name: management-meeting-backend

  # === 1. Database Configuration (Read from .env) ===
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # TURN BACK ON: Run the data.sql file (to fix the 404 error)
    # initialization-mode: always 

  # === 2. Configure Redis (Read from .env) ===
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:} 
      database: ${REDIS_DB}

  # === 3. Configure JPA (Code First) ===
  jpa:
    hibernate:
      # TURNING BACK: This is "Code First"
      ddl-auto: update 
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "Asia/Ho_Chi_Minh"

  # === 4. TURN OFF FLYWAY ===
  flyway:
    enabled: false # Turn off the flyway to avoid conflicts
  
  # === ADDITIONAL: SMTP (Email) Configuration - USE GMAIL ===
  mail:
    protocol: smtp
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# === 5. Swagger UI Configuration ===
springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    path: /swagger-ui.html

# === ADDITIONAL: Application Configuration ===
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
  frontend:
    base-url: ${FRONTEND_BASE_URL}
  backend:
    base-url: ${BACKEND_BASE_URL}


auth:
  service:
    # URL for Resource Server to retrieve JWK Set (containing the Public Key of the Auth Service)
    jwk-set-uri: ${OAuth2_BASE_URL}/oauth2/jwks
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: "${FRONTEND_BASE_URL}/google-callback"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#  pattern:
    # %X{trace_id} and %X{span_id} are variables that OTel Agent automatically injects
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [trace_id=%X{trace_id} span_id=%X{span_id}] - %msg%n"